version: "3"

services:
    web:
        container_name: web
        build: ./src/.
        command: bash ./src/init.sh
        ports:
            - 8000
        restart: always
        volumes:
            - .:/app
        depends_on:
            - database

    nginx:
        build: ./nginx/.
        restart: always
        ports:
            - 80:80
        depends_on:
            - web

    database:
        image: postgres:14.6-alpine
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "5050:80"

volumes:
    pgdata:
