name: Python application

on:
  pull_request:
    branches: [ "master" ]


permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8 pytest-cov
                  pip install -r src/requirements/requirements.txt

            - name: Lint with flake8
              run: |
                  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

            - name: Test with pytest
              run: |
                  pytest --cov=src --cov-report xml

            - name: Python Coverage
              uses: orgoro/coverage@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  coverageFile: coverage.xml
                  thresholdAll: .1
                  thresholdNew: .1
                  thresholdModified: .1
